apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: endgame-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: endgame-app
spec:
  project: default
  source:
    repoURL: https://github.com/sumzzgit/endgame_k8s_argocd.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true

