apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-k8s-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "${SECRET_NAME}" 
        objectType: "secretsmanager"
        jmesPath:
          - path: db_user
            objectAlias: db_user1   
          - path: db_pass
            objectAlias: db_pass1
          - path: db_host
            objectAlias: db_host1
          - path: db
            objectAlias: db
          - path: backend_url
            objectAlias: backend_url1
  secretObjects:
   - secretName: endgame-secret
     type: Opaque
     data:
      - objectName: db_user1
        key: username_01
      - objectName: db_pass1
        key: password_01
      - objectName: db_host1
        key: host_01
      - objectName: db
        key: db_01
      - objectName: backend_url1
        key: backend_url_01
