
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-k8s-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "${SECRET_NAME}" 
        objectType: "secretsmanager"
        jmesPath:
          - path: ${DB_USER}
            objectAlias: db_user   
          - path: password
            objectAlias: ${DB_PASS}
          - path: host
            objectAlias: ${DB_HOST}
          - path: ${DB}
            objectAlias: db
          - path: ${BACKEND_URL}
            objectAlias: backend_url
  secretObjects:
   - secretName: endgame-secret
     type: Opaque
     data:
      - objectName: db_user
        key: username_01
      - objectName: db_pass
        key: password_01
      - objectName: db_host
        key: host_01
      - objectName: db
        key: db_01
      - objectName: backend_url
        key: backend_url_01
