
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-k8s-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "endgame" 
        objectType: "secretsmanager"
        jmesPath:
          - path: admin
            objectAlias: db_user   
          - path: password
            objectAlias: sumit360
          - path: host
            objectAlias: database-1.c1waeq4gymb5.ap-south-1.rds.amazonaws.com
          - path: endgame
            objectAlias: db
          - path: http://backend:5000
            objectAlias: backend_url
  secretObjects:
   - secretName: endgame-secret
     type: Opaque
     data:
      - objectName: db_user
        key: username_01
      - objectName: db_pass
        key: password_01
      - objectName: db_host
        key: host_01
      - objectName: db
        key: db_01
      - objectName: backend_url
        key: backend_url_01
